### ISSUE TITLE
Sytanx Error (w/ python 2.7.4 & 2.7.9)

### ISSUE THREAD

**Issue by jhdmpp** [denys/lastexport#1]
_lastexport.py:142: SyntaxWarning: name 'date' is used prior to global declaration
global counter, date, day, trackdict_

Fixing this still returns a 403: Forbidden error. Did Last.FM change their API auth requirements since this was made, maybe?

**Comment by idx3d** [comment]
@UdinRex hm.. yes, maybe, but there is no API used, this script simply parses contents of the last.fm pages.

**Comment by hugovk** [comment]
#2 is a PR to fix the SyntaxWarning.

I didn't see any 403 error, it worked fine for `-t scrobbles` and `-t loved`, but `-t banned` returns:

```
Exception occured, retrying in 1s: HTTP Error 400: Bad Request
Exception occured, retrying in 5s: HTTP Error 400: Bad Request
```

I wouldn't worry about that right now, as Last.fm has shipped the beta version which has also broken the API too: https://getsatisfaction.com/lastfm/topics/thread-of-revelation-collection-of-information-about-missing-features

**Comment by idx3d** [comment]
Fixed by @hugovk.
